import fs from 'node:fs';
import path from 'node:path';
import { configSchema, type Config } from '../../../core/config.js';
import { SboxError } from '../../../core/errors.js';
import { MODEL_PROFILES, resolveModel, hostAgentName } from '../../../core/model-policy.js';
import { assetsDir, exists, readText } from '../../../core/paths.js';
import { ROLES } from '../../../core/phases.js';
import { loadRoleDescription, loadRoleText } from '../../../core/roles.js';
import { READ_ONLY_ROLES } from '../../../core/runner.js';
import { skillsForHost, skillsForRole, type SkillDefinition } from '../../../core/skills.js';

const START = '<!-- sbox:begin -->';
const END = '<!-- sbox:end -->';
const GENERATED = '# Generated by @spec-box/sdd; run sbox host install --target codex';

// JSON basic strings are TOML-compatible except form feed and literal DEL.
export const tomlString = (s: string) => JSON.stringify(s).replace(/\\(?:["\\/bfnrt]|u[0-9a-fA-F]{4})/g, escape => escape === '\\f' ? '\\u000c' : escape).replace(/\x7f/g, '\\u007f');

export function updateAgentsSection(text: string, body: string): string {
  const starts = text.split(START).length - 1;
  const ends = text.split(END).length - 1;
  const section = `${START}\n${body.trim()}\n${END}`;
  if (!starts && !ends) return `${text}${text && !text.endsWith('\n') ? '\n' : ''}${text ? '\n' : ''}${section}\n`;
  if (starts !== 1 || ends !== 1 || text.indexOf(END) < text.indexOf(START)) {
    throw new SboxError('HOST_SECTION_INVALID', 'Повреждён раздел sbox в AGENTS.md: нужны ровно одна пара sbox:begin / sbox:end.');
  }
  return text.slice(0, text.indexOf(START)) + section + text.slice(text.indexOf(END) + END.length);
}

/** Build all output before writing, preserving user config and unrelated AGENTS.md content. */
export function codexMaterials(root: string, config: Config | undefined, skills: SkillDefinition[]): Map<string, string> {
  const cfg = config ?? configSchema.parse({ version: 1, spec: { adapter: 'spec-box' } });
  const template = readText(path.join(assetsDir(), 'hosts', 'codex', 'agent.md'));
  const files = new Map<string, string>();
  for (const role of ROLES.filter(r => r !== 'distiller')) {
    const roleSkills = skillsForRole(skillsForHost(skills, 'codex'), role);
    const values: Record<string, string> = {
      role, body: loadRoleText(root, role).trim(),
      skills: roleSkills.map(s => `- .agents/skills/${s}/SKILL.md`).join('\n'),
    };
    const instructions = template.replace(/\{\{(\w+)\}\}/g, (_, key: string) => values[key] ?? '');
    for (const profile of [undefined, ...MODEL_PROFILES]) {
      const execution = resolveModel(cfg, 'codex', role, undefined, profile);
      const name = profile ? hostAgentName(role, profile) : `sbox-${role}`;
      const file = path.join(root, '.codex', 'agents', `${name}.toml`);
      if (exists(file) && !readText(file).startsWith(GENERATED)) {
        throw new SboxError('HOST_AGENT_CONFLICT', `Файл ${file} не создан sbox; переименуйте его перед установкой.`);
      }
      files.set(file, `${GENERATED}\n` + Object.entries({
        name, description: loadRoleDescription(root, role), model: execution.model,
        model_reasoning_effort: execution.effort,
        sandbox_mode: READ_ONLY_ROLES.has(role) ? cfg.runner.codex.sandboxRead : cfg.runner.codex.sandboxWrite,
        developer_instructions: instructions,
      }).map(([key, value]) => `${key} = ${tomlString(value)}`).join('\n') + '\n');
    }
  }
  const agentsFile = path.join(root, 'AGENTS.md');
  if (fs.existsSync(agentsFile) && fs.lstatSync(agentsFile).isSymbolicLink()) {
    throw new SboxError('HOST_SECTION_SYMLINK', 'AGENTS.md является ссылкой; sbox не изменяет её целевой файл.');
  }
  files.set(agentsFile, updateAgentsSection(exists(agentsFile) ? readText(agentsFile) : '', readText(path.join(assetsDir(), 'hosts', 'codex', 'AGENTS.md'))));
  return files;
}
